# Generated by Django 3.2.3 on 2021-11-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_list',
            name='tag4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ad_list',
            name='tmp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
